# Generated by Django 3.2.6 on 2021-09-04 19:34

from django.conf import settings
from django.db import migrations


def create_user(apps, schema):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    User.objects.create_superuser("admin", "admin@gmail.com", "1")
    User.objects.create_superuser("user", "user@gmail.com", "1")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_user, None)
    ]
